version: '2.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - http_proxy
      - https_proxy
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=${DISCOVERY_TYPE}
      - bootstrap.memory_lock=${BOOTSTRAP_MEMORY_LOCK}
      - xpack.security.enabled=${XPACK_SECURITY_ENABLED}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ES_JAVA_OPTS
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${ES_MEM_LIMIT}
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elastic
    restart: unless-stopped

  kibana:
    build:
      context: ./
      args:
        - WEB_SOCKET_PORT=${WEB_SOCKET_PORT:-3000}
    ports:
      - 5601:5601
      - 5603:5603
      - ${WEB_SOCKET_PORT:-3000}:3000
    environment:
      - http_proxy
      - https_proxy
      - ELASTICSEARCH_USERNAME=${KIBANA_SYSTEM}
      - SERVER_BASEPATH=${KIBANA_SERVER_BASEPATH:-/kibana}
      - ELASTICSEARCH_PASSWORD
      - KBN_OPTIMIZER_THEMES=v8light
      - KIBANA_VERSION
      - SMTP_HOST=maildev
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_IGNORE_TLS=${SMTP_IGNORE_TLS:-true}
      - SMTP_REJECT_UNAUTHORIZED=${SMTP_REJECT_UNAUTHORIZED:-false}
    volumes:
      - ./kibana/kibana.dev.yml:/home/kbn-dev/kibana/config/kibana.dev.yml:ro
      - ./src:/home/kbn-dev/kibana/plugins/ezreporting
    networks:
      - elastic

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
    networks:
      - elastic

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge